### ISSUE TITLE
Chrome tab not closing properly when using Nodemon

### ISSUE THREAD

**Issue by jadengore** [june07/NIM#1]
I have an issue where restarting my server through Nodemon does not close the tab, but instead renders this error message:

<img width="451" alt="screenshot 2016-12-17 21 19 28" src="https://cloud.githubusercontent.com/assets/1921464/21292539/c9f6403a-c4bd-11e6-9ca8-5103d0c02992.png">

After looking through the source code I think I've isolated the problem [to here](https://github.com/june07/NIM/blob/master/background.js#L88-L113). The `catch` for the HTTP request does not consider a valid case where the debug server is not down, but the ID of the debugger websocket changes.

A proposed solution would be to store the unique identifier for each devtools session, and check if that identifier is in the returned JSON from the localhost debug server. Requests coulda also be minimized by making the request only once and filtering `$scope.devToolsSessions` according to the returned identifiers.

I'd be willing to PR this in the next couple days with your OK @june07 

Edit: Initial conversation about this issue can be found [here](https://github.com/remy/nodemon/issues/903#issuecomment-267803859).

**Comment by june07** [comment]
First of all, good work on the detail provided thus far.  Thank you.  Can
you tell me more about your dev environment, including Node version.  I'm
trying to understand "where the debug server is not down, but the ID of the
debugger websocket changes."  I havent seen this behavior?  Why/how is the
websocket changing without a restart of the debugger/node process?

**Comment by jadengore** [comment]
@june07 Dev environment is Node 6.9.1, I'm using [`fly`] and [`fly-nodemon`] to run Nodemon, and I pass inspect in as a `nodeArgs` option to Nodemon. Since the Fly process continues running the server hosting the websockets comes back up before the 3000ms check, I think that could be why your code is not detecting a change.

It might be easier if I show you in code... I have a PR ready that shows the solution I have in mind.

**Comment by june07** [comment]
Edward,

Nice.  That's it!  I've merged the PR.

**Comment by jadengore** [comment]
Thanks @june07, let me know when you update this on the Chrome Web Store.

**Comment by DarrylD** [comment]
I'm having the same issue, is the new update pushed? 

When i start my server, i have to goto the url manually, and when nodemon restarts from change, I just get the error.

**Comment by june07** [comment]
The current version is 0.9.0.  Do you have the setting on manual or auto?
Also how is the auto close setting configured?

On Dec 25, 2016 10:57 PM, "Darryl Dexter" <notifications@github.com> wrote:

I'm having the same issue, is the new update pushed?

When i start my server, i have to goto the url manually, and when nodemon
restarts from change, I just get the error.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/june07/NIM/issues/1#issuecomment-269173050>, or mute
the thread

**Comment by DarrylD** [comment]
Sorry, commented before I worked it out. Needed to update chrome apparently... Thx, awesome plugin!

**Comment by june07** [comment]
No worries.  Glad to help.  And thank you for the positive feedback!  If
it's not too much trouble, a review and/or rating at the Web Store would
help out greatly.

On Dec 25, 2016 11:31 PM, "Darryl Dexter" <notifications@github.com> wrote:

Sorry, commented before I worked it out. Needed to update chrome
apparently... Thx, awesome plugin!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/june07/NIM/issues/1#issuecomment-269176827>, or mute
the thread

**Comment by duanjun** [comment]
macOS sierra 10.12.2 . chrome  55.0.2883.95 (64-bit)
had the same problem

**Comment by june07** [comment]
Are you using the current version?  Any additional information you can provide will be helpful in figuring out what is going on.  I'm sure you have already but in case not, please read through the entire thread as some information may be helpful.

**Comment by duanjun** [comment]
it works now . thanks.  
maybe my setting is not right !
