### ISSUE TITLE
Any way to avoid the window re-opening

### ISSUE THREAD

**Issue by wesbos** [june07/NIM#11]
Hello! huge huge huge thank you for NIM - it's just what we need to make node debugging have a smooth workflow. 

I was wondering if it's at all possible to just change the page to the new inspector window.

The problem I'm having is that when I save a file, I have nodemon restart my process. 

Once it restarts, the window closes and a new one opens up. I love if I could just keep my window open at all times and have it refresh itself and move itself to the new window. 

Let me know  -thanks again!

**Comment by june07** [comment]
Wes,

Thank you for the positive feedback!

I will certainly give this a closer look as soon as time permits.  I've had
a few others express the same desire so I know it would be time well spent.

(plug) If you could give a 5-star review and/or G+1 that would be much
appreciated.  I'd like to reach as many developers as possible and the
ratings help.


On Feb 28, 2017 11:59 AM, "Wes Bos" <notifications@github.com> wrote:

Hello! huge huge huge thank you for NIM - it's just what we need to make
node debugging have a smooth workflow.

I was wondering if it's at all possible to just change the page to the new
inspector window.

The problem I'm having is that when I save a file, I have nodemon restart
my process.

Once it restarts, the window closes and a new one opens up. I love if I
could just keep my window open at all times and have it refresh itself and
move itself to the new window.

Let me know -thanks again!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/june07/NIM/issues/11>, or mute the thread

**Comment by june07** [comment]
Wes,

Just pushed the change to the Chrome Web Store!  Let me know what you think.

**Comment by june07** [comment]
Re-opened due to:
NIM tab is reloaded every seconds. #12

**Comment by wesbos** [comment]
I can't seem to get the dev tools to open at all now - either manual or automatic

**Comment by june07** [comment]
I pushed another update a few hours ago.  Can you confirm it's resolved
your issue...
