### ISSUE TITLE
How do you control auto close?

### ISSUE THREAD

**Issue by wookiem** [june07/NIM#4]
Thanks for this tool -- very handy.  

How do you control the auto-close feature?  I assume that enabling this option will kill any instances of node --inspect.  Correct?  I'm hoping that it will deal with the "Unable to open devtools socket: address already in use" that I get from time to time.

Does it auto-close simply by closing the tab that NIM is running in?

**Comment by june07** [comment]
Auto close will close the tab or window that DevTools is running in once
the socket is disconnected.  So instead of just hanging with the "Unable to
open devtools" message, the window/tab will be closed automatically.  Does
that answer your question?



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=667@onezerohosting.com&idSignature=22>

**Comment by wookiem** [comment]
Ah, that's very slick.  

I notice that sometimes `control-c` doesn't seem to kill the `node --inspect ` task.  Will closing the terminal session in this case cause auto-close to kick in?

**Comment by june07** [comment]
Were you able to resolve this?  I believe that closing the teminal would
end the process which should then in turn cause the tab or window to close.

On Dec 24, 2016 2:17 AM, "wookiem" <notifications@github.com> wrote:

Ah, that's very slick.

I notice that sometimes control-c doesn't seem to kill the node --inspect
task. Will closing the terminal session in this case cause auto-close to
kick in?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/june07/NIM/issues/4#issuecomment-269078335>, or mute
the thread

**Comment by wookiem** [comment]
No, closing the terminal doesn't seem to kill the task.  I had to use `ps -ax | grep inspect ` to identify the task and then use `kill - 9 <task id>`

However, I am now able to avoid this issue completely by making sure that my node app is not paused on a breakpoint when I close the chrome node debugger tab.  If I do this, then everything works perfectly.

So, everything is setup perfectly now and your tool is a very nice time-saver.
