### ISSUE TITLE
Latest Chrome update gets NIM stuck in a loop

### ISSUE THREAD

**Issue by samartioli** [june07/NiM#45]
Chrome just auto updated to Version 65.0.3325.146 (Official Build) (64-bit)
 and now I get this when NIM launches

![nim-loop](https://user-images.githubusercontent.com/1176093/37244406-9c33d938-2456-11e8-8fb5-0f69bf652c1d.gif)

But going directly to `chrome://inspect` works. Also looks like there is a new option in `chrome://inspect` to `Open dedicated DevTools for Node`

**Comment by june07** [comment]
Unable to duplicate.  Sounds like you solved the problem.  Cheers.

**Comment by samartioli** [comment]
Still not able to get NIM working. Work around is to just manually launch DevTools for Node via `chrome://inspect`
I would like to get NIM working again and auto launching for me, but if you're unable to reproduce it, it must be something on my system.

**Comment by june07** [comment]
Try decreasing the polling time from .5 to 1 or more seconds... maybe that
will help?

**Comment by samartioli** [comment]
that worked... weird... Thanks! Awesome tool.

**Comment by june07** [comment]
Glad it worked.  Feel free to throw 5 (stars) at it at the Chrome store
https://june07.com/nim.

;)

On Mar 13, 2018 6:54 PM, "samartioli" <notifications@github.com> wrote:

that worked... weird... Thanks! Awesome tool.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/june07/NiM/issues/45#issuecomment-372878380>, or mute
the thread
