### ISSUE TITLE
Sourcemaps aren't rectified

### ISSUE THREAD

**Issue by anied** [june07/NiM#51]
When using the plug-in, sourcemaps for babel aren't been mapped to the source.  This is similar in _symptom_ to [NodeJS issue #8369](https://github.com/nodejs/node/issues/8369) -- however, when I access the dev tools using `chrome://inspect` the issue is not seen.

Love this plug-in and would be happy to help however is needed-- I can perform more info as needed and would be willing to take a crack at opening a PR if I could get some direction.

Thanks.

**Comment by june07** [comment]
When you say NiM "introduce this issue when it otherwise wouldn't be present--" what do you mean exactly?

Are you saying that chrome://inspect behaves differently based NiM being installed or not?

**Comment by anied** [comment]
Sorry if I was unclear: I am saying the presence of NiM _does_ affect the behavior.

If I have NiM installed, the Chrome inspector will be automatically opened when I start a node task in debug mode-- however, while sourcemaps will be detected they won't map sourcefiles.

If I then disable NiM in Chrome and restart the same node task in debug mode, and navigate to `chrome://inspect` to open the chrome dev tools for node, sourcefiles will be mapped properly.

**Comment by june07** [comment]
Well first of all, thank you.  Appreciate the feedback.  Certainly if this is the case, it's a big concern that I would like to get resolved.

I haven't delved too deeply into the Chrome source to see what code exactly is behind chrome://inspect, so I'm afraid I can't speak to the difference between that and devtools://devtools/bundled/inspector.html.  I have a suspicion that the problem may be in the Chrome DevTools inspector code...

As I recall, I looked a bit into the chrome://inspect feature but didn't see a correlation between the two.  Maybe that would help to know if there is/isn't and further to ask the Chrome dev team about the bundled inspector code if it's shown that the issue here is also related to it.

Hopefully that all makes sense... typing this on my phone, after having a few glasses of wine this evening.

-Cheers

**Comment by jdalton** [comment]
Just popping in to say that I recently ran into this too. NiM is configured to auto-open a window. In its inspector inline source maps are broken. However, that doesn't stop `chrome://inspect` from working.

![demo](https://user-images.githubusercontent.com/4303/42148322-9f41bd96-7d86-11e8-813d-b0cd173ce148.gif)

**Comment by jcollum** [comment]
I've seen this too but it's sporadic. I don't have consistent steps to repro.

**Comment by june07** [comment]
http://june07.com/blog/nim-custom-devtools-url/

I believe using a different DevTools version in cases where this comes up (dependant upon which version of chrome/node you are running) will resolve the issue.

**Comment by SagaciousLittle** [comment]
> 使用插件时，babel 的源映射不会映射到源。这与 NodeJS 问题 #8369 的症状相似——[但是](https://github.com/nodejs/node/issues/8369)_，_当我使用该问题访问开发工具时，看不到该问题。[](https://github.com/nodejs/node/issues/8369)`chrome://inspect`
> 
> 喜欢这个插件，并且很乐意提供帮助——我可以根据需要执行更多信息，如果我能得到一些指导，我愿意尝试打开 PR。
> 
> 谢谢。



> When using the plug-in, sourcemaps for babel aren't been mapped to the source. This is similar in _symptom_ to [NodeJS issue #8369](https://github.com/nodejs/node/issues/8369) -- however, when I access the dev tools using `chrome://inspect` the issue is not seen.
> 
> Love this plug-in and would be happy to help however is needed-- I can perform more info as needed and would be willing to take a crack at opening a PR if I could get some direction.
> 
> Thanks.

hello, is there any updates on this issure?

**Comment by june07** [comment]
https://github.com/june07/NiM/issues/98#issuecomment-848441914

See if that helps...
